// Automatically generated by astro-icon
// 764710333e55205464f182b2a88d2688479ef2ab723c8eb42db508aa55b9a699

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "email"
		| "github"
		| "link"
		| "linkedin"
		| "love"
		| "moon"
		| "sun"
		| "twitter";
}